/**
 * Visual Design Tokens — TypeScript Constants
 * Generated by compile-tokens.ts v1.1.0
 * Source: tokens.json
 * Do not edit directly.
 */

export const tokens = {
  "primitive": {
    "color": {
      "blue": {
        "300": "#4d9fff",
        "500": "#0066cc",
        "600": "#0052a3",
        "700": "#003e8a"
      },
      "gray": {
        "400": "#9ca3af",
        "500": "#6c757d",
        "600": "#495057"
      },
      "green": {
        "300": "#34d399",
        "500": "#28a745",
        "700": "#146829"
      },
      "amber": {
        "300": "#fbbf24",
        "500": "#ffc107",
        "700": "#664d03"
      },
      "red": {
        "300": "#f87171",
        "500": "#dc3545",
        "700": "#a71d2a"
      },
      "crimson": {
        "50": "#fdeef0",
        "200": "#f4c2c9",
        "300": "#ff6b6b",
        "600": "#c8102e",
        "700": "#9b0c23",
        "800": "#6d0819",
        "900": "#3a0f18"
      },
      "cobalt": {
        "50": "#eaf1fe",
        "200": "#bcd3f8",
        "300": "#6fa8ff",
        "600": "#0b4fcf",
        "700": "#083a99",
        "800": "#052866",
        "900": "#0b1f42"
      },
      "slate": {
        "50": "#eef1f5",
        "200": "#cbd4e0",
        "300": "#9aa8bd",
        "600": "#546376",
        "700": "#3d4857",
        "800": "#2b3442",
        "900": "#1e2532"
      },
      "neutral": {
        "0": "#ffffff",
        "50": "#f9fafb",
        "100": "#f2f4f7",
        "200": "#e5e8ee",
        "800": "#1c2331",
        "900": "#111827",
        "950": "#000000"
      },
      "ink": {
        "900": "#1a1a1a"
      }
    },
    "font": {
      "sans": "Inter, system-ui, -apple-system, sans-serif",
      "mono": "Fira Code, monospace"
    },
    "font-size": {
      "sm": "0.875rem",
      "base": "1rem",
      "lg": "1.25rem",
      "xl": "1.5rem"
    },
    "space": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem",
      "xl": "2rem"
    },
    "radius": {
      "sm": "4px",
      "md": "8px",
      "lg": "16px"
    },
    "elevation": {
      "sm": "0 1px 2px rgba(0, 0, 0, 0.05)",
      "md": "0 4px 6px rgba(0, 0, 0, 0.1)",
      "lg": "0 10px 15px rgba(0, 0, 0, 0.1)"
    },
    "duration": {
      "fast": "150ms",
      "normal": "250ms",
      "slow": "400ms"
    }
  },
  "semantic": {
    "color": {
      "primary": "var(--color-blue-500)",
      "secondary": "var(--color-gray-500)",
      "success": "var(--color-green-500)",
      "warning": "var(--color-amber-500)",
      "danger": "var(--color-red-500)",
      "background": "var(--color-neutral-0)",
      "surface": "var(--color-neutral-0)",
      "surface-sunken": "var(--color-neutral-100)",
      "border": "var(--color-neutral-200)",
      "text": "var(--color-ink-900)",
      "text-muted": "var(--color-slate-600)",
      "value-up": "var(--color-crimson-600)",
      "value-up-bg": "var(--color-crimson-50)",
      "value-up-border": "var(--color-crimson-200)",
      "value-down": "var(--color-cobalt-600)",
      "value-down-bg": "var(--color-cobalt-50)",
      "value-down-border": "var(--color-cobalt-200)",
      "value-flat": "var(--color-slate-600)",
      "value-flat-bg": "var(--color-slate-50)",
      "value-flat-border": "var(--color-slate-200)",
      "stale": "var(--color-slate-600)",
      "stale-bg": "var(--color-slate-50)",
      "stale-border": "var(--color-slate-200)",
      "estimated": "var(--color-slate-600)",
      "estimated-bg": "var(--color-slate-50)",
      "estimated-border": "var(--color-slate-200)"
    },
    "typography": {
      "font-family": {
        "sans": "var(--font-sans)",
        "mono": "var(--font-mono)"
      },
      "font-size": {
        "sm": "var(--font-size-sm)",
        "base": "var(--font-size-base)",
        "lg": "var(--font-size-lg)",
        "xl": "var(--font-size-xl)"
      }
    },
    "spacing": {
      "xs": "var(--space-xs)",
      "sm": "var(--space-sm)",
      "md": "var(--space-md)",
      "lg": "var(--space-lg)",
      "xl": "var(--space-xl)"
    },
    "border-radius": {
      "sm": "var(--radius-sm)",
      "md": "var(--radius-md)",
      "lg": "var(--radius-lg)"
    },
    "shadow": {
      "sm": "var(--elevation-sm)",
      "md": "var(--elevation-md)",
      "lg": "var(--elevation-lg)"
    },
    "motion": {
      "duration-fast": "var(--duration-fast)",
      "duration-normal": "var(--duration-normal)",
      "duration-slow": "var(--duration-slow)"
    },
    "target": {
      "size": "2.75rem"
    },
    "focus": {
      "ring": "2px solid var(--color-primary)",
      "ring-offset": "2px"
    }
  }
} as const;

export type Tokens = typeof tokens;

export const CSS_VARS = {
  "primitive": {
    "color": {
      "blue": {
        "300": "var(--color-blue-300)",
        "500": "var(--color-blue-500)",
        "600": "var(--color-blue-600)",
        "700": "var(--color-blue-700)"
      },
      "gray": {
        "400": "var(--color-gray-400)",
        "500": "var(--color-gray-500)",
        "600": "var(--color-gray-600)"
      },
      "green": {
        "300": "var(--color-green-300)",
        "500": "var(--color-green-500)",
        "700": "var(--color-green-700)"
      },
      "amber": {
        "300": "var(--color-amber-300)",
        "500": "var(--color-amber-500)",
        "700": "var(--color-amber-700)"
      },
      "red": {
        "300": "var(--color-red-300)",
        "500": "var(--color-red-500)",
        "700": "var(--color-red-700)"
      },
      "crimson": {
        "50": "var(--color-crimson-50)",
        "200": "var(--color-crimson-200)",
        "300": "var(--color-crimson-300)",
        "600": "var(--color-crimson-600)",
        "700": "var(--color-crimson-700)",
        "800": "var(--color-crimson-800)",
        "900": "var(--color-crimson-900)"
      },
      "cobalt": {
        "50": "var(--color-cobalt-50)",
        "200": "var(--color-cobalt-200)",
        "300": "var(--color-cobalt-300)",
        "600": "var(--color-cobalt-600)",
        "700": "var(--color-cobalt-700)",
        "800": "var(--color-cobalt-800)",
        "900": "var(--color-cobalt-900)"
      },
      "slate": {
        "50": "var(--color-slate-50)",
        "200": "var(--color-slate-200)",
        "300": "var(--color-slate-300)",
        "600": "var(--color-slate-600)",
        "700": "var(--color-slate-700)",
        "800": "var(--color-slate-800)",
        "900": "var(--color-slate-900)"
      },
      "neutral": {
        "0": "var(--color-neutral-0)",
        "50": "var(--color-neutral-50)",
        "100": "var(--color-neutral-100)",
        "200": "var(--color-neutral-200)",
        "800": "var(--color-neutral-800)",
        "900": "var(--color-neutral-900)",
        "950": "var(--color-neutral-950)"
      },
      "ink": {
        "900": "var(--color-ink-900)"
      }
    },
    "font": {
      "sans": "var(--font-sans)",
      "mono": "var(--font-mono)"
    },
    "font-size": {
      "sm": "var(--font-size-sm)",
      "base": "var(--font-size-base)",
      "lg": "var(--font-size-lg)",
      "xl": "var(--font-size-xl)"
    },
    "space": {
      "xs": "var(--space-xs)",
      "sm": "var(--space-sm)",
      "md": "var(--space-md)",
      "lg": "var(--space-lg)",
      "xl": "var(--space-xl)"
    },
    "radius": {
      "sm": "var(--radius-sm)",
      "md": "var(--radius-md)",
      "lg": "var(--radius-lg)"
    },
    "elevation": {
      "sm": "var(--elevation-sm)",
      "md": "var(--elevation-md)",
      "lg": "var(--elevation-lg)"
    },
    "duration": {
      "fast": "var(--duration-fast)",
      "normal": "var(--duration-normal)",
      "slow": "var(--duration-slow)"
    }
  },
  "semantic": {
    "color": {
      "primary": "var(--color-primary)",
      "secondary": "var(--color-secondary)",
      "success": "var(--color-success)",
      "warning": "var(--color-warning)",
      "danger": "var(--color-danger)",
      "background": "var(--color-background)",
      "surface": "var(--color-surface)",
      "surface-sunken": "var(--color-surface-sunken)",
      "border": "var(--color-border)",
      "text": "var(--color-text)",
      "text-muted": "var(--color-text-muted)",
      "value-up": "var(--color-value-up)",
      "value-up-bg": "var(--color-value-up-bg)",
      "value-up-border": "var(--color-value-up-border)",
      "value-down": "var(--color-value-down)",
      "value-down-bg": "var(--color-value-down-bg)",
      "value-down-border": "var(--color-value-down-border)",
      "value-flat": "var(--color-value-flat)",
      "value-flat-bg": "var(--color-value-flat-bg)",
      "value-flat-border": "var(--color-value-flat-border)",
      "stale": "var(--color-stale)",
      "stale-bg": "var(--color-stale-bg)",
      "stale-border": "var(--color-stale-border)",
      "estimated": "var(--color-estimated)",
      "estimated-bg": "var(--color-estimated-bg)",
      "estimated-border": "var(--color-estimated-border)"
    },
    "typography": {
      "font-family": {
        "sans": "var(--typography-font-family-sans)",
        "mono": "var(--typography-font-family-mono)"
      },
      "font-size": {
        "sm": "var(--typography-font-size-sm)",
        "base": "var(--typography-font-size-base)",
        "lg": "var(--typography-font-size-lg)",
        "xl": "var(--typography-font-size-xl)"
      }
    },
    "spacing": {
      "xs": "var(--spacing-xs)",
      "sm": "var(--spacing-sm)",
      "md": "var(--spacing-md)",
      "lg": "var(--spacing-lg)",
      "xl": "var(--spacing-xl)"
    },
    "border-radius": {
      "sm": "var(--border-radius-sm)",
      "md": "var(--border-radius-md)",
      "lg": "var(--border-radius-lg)"
    },
    "shadow": {
      "sm": "var(--shadow-sm)",
      "md": "var(--shadow-md)",
      "lg": "var(--shadow-lg)"
    },
    "motion": {
      "duration-fast": "var(--motion-duration-fast)",
      "duration-normal": "var(--motion-duration-normal)",
      "duration-slow": "var(--motion-duration-slow)"
    },
    "target": {
      "size": "var(--target-size)"
    },
    "focus": {
      "ring": "var(--focus-ring)",
      "ring-offset": "var(--focus-ring-offset)"
    }
  }
} as const;

export type CssVars = typeof CSS_VARS;

export const themes = {
  "dark": {
    "color": {
      "primary": "var(--color-blue-300)",
      "secondary": "var(--color-gray-400)",
      "success": "var(--color-green-300)",
      "warning": "var(--color-amber-300)",
      "danger": "var(--color-red-300)",
      "background": "var(--color-neutral-900)",
      "surface": "var(--color-neutral-800)",
      "surface-sunken": "var(--color-neutral-900)",
      "border": "var(--color-slate-800)",
      "text": "var(--color-neutral-50)",
      "text-muted": "var(--color-slate-300)",
      "value-up": "var(--color-crimson-300)",
      "value-up-bg": "var(--color-crimson-900)",
      "value-up-border": "var(--color-crimson-800)",
      "value-down": "var(--color-cobalt-300)",
      "value-down-bg": "var(--color-cobalt-900)",
      "value-down-border": "var(--color-cobalt-800)",
      "value-flat": "var(--color-slate-300)",
      "value-flat-bg": "var(--color-slate-900)",
      "value-flat-border": "var(--color-slate-800)",
      "stale": "var(--color-slate-300)",
      "stale-bg": "var(--color-slate-900)",
      "stale-border": "var(--color-slate-800)",
      "estimated": "var(--color-slate-300)",
      "estimated-bg": "var(--color-slate-900)",
      "estimated-border": "var(--color-slate-800)"
    },
    "shadow": {
      "sm": "0 1px 2px rgba(0, 0, 0, 0.3)",
      "md": "0 4px 6px rgba(0, 0, 0, 0.4)",
      "lg": "0 10px 15px rgba(0, 0, 0, 0.5)"
    }
  },
  "high-contrast": {
    "color": {
      "primary": "var(--color-blue-700)",
      "secondary": "var(--color-gray-600)",
      "success": "var(--color-green-700)",
      "warning": "var(--color-amber-700)",
      "danger": "var(--color-red-700)",
      "background": "var(--color-neutral-0)",
      "surface": "var(--color-neutral-0)",
      "surface-sunken": "var(--color-neutral-50)",
      "border": "var(--color-slate-700)",
      "text": "var(--color-neutral-950)",
      "text-muted": "var(--color-slate-700)",
      "value-up": "var(--color-crimson-700)",
      "value-up-bg": "var(--color-neutral-0)",
      "value-up-border": "var(--color-crimson-700)",
      "value-down": "var(--color-cobalt-700)",
      "value-down-bg": "var(--color-neutral-0)",
      "value-down-border": "var(--color-cobalt-700)",
      "value-flat": "var(--color-slate-700)",
      "value-flat-bg": "var(--color-neutral-0)",
      "value-flat-border": "var(--color-slate-700)",
      "stale": "var(--color-slate-700)",
      "stale-bg": "var(--color-neutral-0)",
      "stale-border": "var(--color-slate-700)",
      "estimated": "var(--color-slate-700)",
      "estimated-bg": "var(--color-neutral-0)",
      "estimated-border": "var(--color-slate-700)"
    }
  }
} as const;

export type Themes = typeof themes;

export default tokens;
